specVersion: 0.2.0
name: astarStatsAggregateBlockData
version: 0.0.1
description: >-
  A astar network blockchain aggregation data.
repository: 'https://github.com/AstarStats/astarsts-aggregate-block-data'
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x9eb76c5184c4ab8679d2d5d819fdf90b9c001403e9e17da2e14b6d8aec4029c6'
  endpoint: 'wss://astar.api.onfinality.io/public-ws'
  dictionary: 'https://api.subquery.network/sq/subquery/astar-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler